// global
export const GENERATE_SUPPORT_BUNDLES = 'GENERATE_SUPPORT_BUNDLES'

// volume
export const FETCH_VOLUME = 'FETCH_VOLUME';
export const VOLUME_CONNECT_WS = 'VOLUME_CONNECT_WS'
export const DISCONNECT_VOLUME_WEBSOCKET = 'DISCONNECT_VOLUME_WEBSOCKET'

// EVENTLOG
export const FETCH_EVENTLOG = 'FETCH_EVENTLOG';
export const EVENTLOG_CONNECT_WS = 'EVENTLOG_CONNECT_WS'
export const DISCONNECT_EVENTLOG_WEBSOCKET = 'DISCONNECT_EVENTLOG_WEBSOCKET'

// NODE
export const FETCH_NODE = 'FETCH_NODE';
export const NODE_CONNECT_WS = 'NODE_CONNECT_WS'
export const DISCONNECT_NODE_WEBSOCKET = 'DISCONNECT_NODE_WEBSOCKET'

// NODE
export const FETCH_SETTING = 'FETCH_SETTING';
export const SETTING_CONNECT_WS = 'SETTING_CONNECT_WS'
export const DISCONNECT_SETTING_WEBSOCKET = 'DISCONNECT_SETTING_WEBSOCKET'
